[project]
authors = ["Scott Henderson <scottyhq@gmail.com>"]
channels = ["conda-forge"]
description = "Notes and code to understand and successfully perform accurate 3D coordinate reference system (CRS) transformations"
name = "3D_CRS_Transformation_Resources"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
website='jupyter book start'

[dependencies]
gdal = ">=3.10.1,<4"
ipython = ">=8.31.0,<9"
geopandas = ">=1.0.1,<2"
xarray = ">=2025.1.1,<2026"
rioxarray = ">=0.17.0,<0.18"
matplotlib = ">=3.10.0,<4"
ipykernel = ">=6.29.5,<7"
libgdal-arrow-parquet = ">=3.10.1,<4"

[pypi-dependencies]
jupyter-book = "==2.0.0a1"
